apiVersion: v1
data:
    enrichers.yaml: |
        order:
            - eos
            - owner
        sources:
            - name: eos
              path: eos-enricher.yaml
            - name: owner
              path: owner-enricher.yaml
            - name: findings-summary
              path: findings-summary-enricher.yaml
            - name: waive-images
              path: waive-images-enricher.yaml
    eos-enricher.yaml: |
        enricher:
            - name: file
              config: eos-eos.yaml
              ref: eos
            - name: hbs
              config: eos-eos_v1.hbs
              ref: ""
    eos-eos.yaml: |
        # Alpine: https://www.alpinelinux.org/releases/
        #
        alpine:
          - version: 3.3.%
            eos: 2017-11-01
          - version: 3.4.%
            eos: 2018-05-01
          - version: 3.5.%
            eos: 2018-11-01
          - version: 3.6.%
            eos: 2019-05-01
          - version: 3.7.%
            eos: 2019-11-01
          - version: 3.8.%
            eos: 2020-05-01
          - version: 3.9.%
            eos: 2020-11-01
          - version: 3.10.%
            eos: 2021-05-01
          - version: 3.11.%
            eos: 2021-11-01
          - version: 3.12.%
            eos: 2022-05-01
          - version: 3.13.%
            eos: 2022-11-01
          - version: 3.14.%
            eos: 2023-05-01
          - version: 3.15.%
            eos: 2023-11-01
          - version: 3.16.%
            eos: 2024-05-23
          - version: 3.17.%
            eos: 2024-11-22
          - version: 3.18.%
            eos: 2025-05-09
          - version: 3.19.%
            eos: 2025-11-01
          - version: 3.20.%
            eos: 2026-04-01
          - version: 3.21.%
            eos: 2026-11-01
          - version: 3.22.%
            eos: 2027-05-01

        # Redhat
        #   https://access.redhat.com/support/policy/updates/errata/
        #   https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,OpenShift%20Container%20Platform%204

        # 2024-07-03 Update Redhat 8.10, 9.10
        rhel:
          - version: 7.7
            eos: 2019-08-06
          - version: 7.8
            eos: 2019-08-06
          - version: 7.9
            eos: 2019-08-06

          - version: 8.0
            eos: 2020-05-31
          - version: 8.1
            eos: 2021-12-31
          - version: 8.2
            eos: 2022-05-31
          - version: 8.3
            eos: 2021-05-31
          - version: 8.4
            eos: 2023-05-31
          - version: 8.5
            eos: 2022-05-31
          - version: 8.6
            eos: 2024-05-31

          - version: 8.7
            eos: 2023-05-31
          - version: 8.8
            eos: 2025-05-31
          - version: 8.9
            eos: 2024-05-31
          - version: 8.10
            eos: 2029-05-31

          - version: 9.0
            eos: 2024-05-31
          - version: 9.1
            eos: 2023-05-31
          - version: 9.2
            eos: 2025-05-31
          - version: 9.3
            eos: 2024-05-31
          - version: 9.4
            eos: 2026-05-31
          - version: 9.5
            eos: 2025-05-31
          - version: 9.6
            eos: 2027-05-31
          - version: 9.7
            eos: 2026-05-31
          - version: 9.8
            eos: 2028-05-31
          - version: 9.9
            eos: 2027-05-31
          - version: 9.10
            eos: 2032-05-31

        # Centos  https://www.redhat.com/en/topics/linux/centos-linux-eol
        #         https://endoflife.date/centos
        centos:
          - version: 7
            eos: 2020-08-06
          - version: 8
            eos: 2024-06-30

        # Ubuntu
        #   Source: https://endoflife.software/operating-systems/linux/ubuntu
        #
        ubuntu:
          - version: 18.04
            eos: 2023-04-01
          - version: 19.04
            eos: 2020-01-01
          - version: 19.10
            eos: 2020-07-01
          - version: 20.04
            eos: 2025-04-01
          - version: 21.04
            eos: 2022-01-01
          - version: 21.10
            eos: 2022-07-01
          - version: 22.04
            eos: 2027-04-01
          - version: 24.04
            eos: 2029-04-01

        # Debian
        #   Source: https://wiki.debian.org/DebianReleases
        #           https://endoflife.date/debian
        #
        #   EOL for security support!
        #
        debian:
          - version: 8
            eos: 2020-06-30
          - version: 9
            eos: 2020-07-18
          - version: 10
            eos: 2022-09-10
          - version: 11
            eos: 2024-07-01
          - version: 12
            eos: 2026-06-10

        # Mariner | Microsoft Azure Linux
        #   Source:   https://microsoft.github.io/CBL-Mariner/announcing-mariner-2.0/
        #   Releases: https://github.com/microsoft/CBL-Mariner/releases
        mariner:
          - version: 1.0
            eos: 2022-11-23
          - version: 2.0
            eos: 2024-05-23

        # Busybox
        #   Source: https://www.busybox.net/
        #
        #   EOL is set 2 years after release
        busybox:
          - version: 1.31.%
            eos: 2022-05-03

          - version: 1.32.%
            eos: 2022-05-03

          - version: 1.33.%
            eos: 2023-05-03
          - version: 1.34.%
            eos: 2023-09-10
          - version: 1.35.%
            eos: 2023-12-26
          - version: 1.35.%
            eos: 2023-12-26
          - version: 1.36.%
            eos: 2025-05-23

        # Amazon Linux
        # EOL: https://endoflife.date/amazon-linux
        # Source: https://aws.amazon.com/amazon-linux-2/features/
        # Releases: https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-al2.html
        amazonlinux:
          - version: 2
            eos:  2025-06-30
          - version: 2023
            eos:  2029-06-30
    eos-eos_v1.hbs: "distro: {{ .payload.Image.DistroName }}\nversion: {{ .payload.Image.DistroVersion }}\neos: {{ index .meta.eos .payload.Image.DistroName | filter \"version\" \"matchWildcard\" .payload.Image.DistroVersion | map \"field\" \"eos\" | first }}\n  "
    findings-summary-enricher.yaml: |
        enricher:
            - name: starlark
              config: findings-summary-findings-summary.star
              ref: ""
    findings-summary-findings-summary.star: "#!/usr/bin/env star\n\n# Return summary of findings\ndef enrich(input):\n    data = input.payload\n    severity_01_critical = 0\n    severity_02_high = 0\n    severity_03_medium = 0\n    severity_04_low = 0\n    severity_05_negligible = 0\n    if data.Image.Findings == None:\n        print(\"error iterating through findings, value of findings: \" + str(data.Image.Findings))\n    else:\n        for finding in data.Image.Findings:\n            if finding.Severity == \"Critical\":\n                severity_01_critical += 1\n            elif finding.Severity == \"High\":\n                severity_02_high += 1\n            elif finding.Severity == \"Medium\":\n                severity_03_medium += 1\n            elif finding.Severity == \"Low\":\n                severity_04_low += 1\n            elif finding.Severity == \"Negligible\":\n                severity_05_negligible += 1\n    alerted = False\n    if severity_01_critical > 0 or severity_02_high > 0:\n        alerted = True\n    return { \n        \"Severity01Critical\": severity_01_critical,\n        \"Severity02High\": severity_02_high,\n        \"Severity03Medium\": severity_03_medium,\n        \"Severity04Low\": severity_04_low,\n        \"Severity05Negligible\": severity_05_negligible,\n        \"Alerted\": alerted\n    }\n\n"
    owner-enricher.yaml: |
        enricher:
            - name: file
              config: owner-owners.yaml
              ref: owners
            - name: hbs
              config: owner-owners_v1.hbs
              ref: ""
    owner-owners.yaml: |-
        byNamespace:
          - namespace: kube-system
            owner: john@mail.com
          - namespace: default
            owner: jessica@mail.com
    owner-owners_v1.hbs: |
        {{- $contextRoot := .payload.Image.ContextRoots | first }}
        {{- $namespace := ($contextRoot.Contexts | filter "Owner" "startsWith" "pharos-controller" | first).Data.namespace }}
        owner: {{ .meta.owners.byNamespace | filter "namespace" "startsWith" $namespace | map "field" "owner" | first | toYaml | nindent 2 }}
    waive-images-enricher.yaml: |
        enricher:
            - name: starlark
              config: waive-images-waive-images.star
              ref: ""
    waive-images-waive-images.star: "#!/usr/bin/env star\n\n# Return summary of findings\ndef enrich(input):\n    data = input.payload\n    waived = \"false\"\n    namespace = data.Image.ContextRoots[0].Contexts[0].Data.namespace\n    if namespace == \"kube-system\":\n       waived = \"true\"\n    if namespace == \"cattle-system\":\n       waived = \"true\"\n    if namespace == \"cattle-fleet-system\":\n       waived = \"true\"\n    if namespace == \"cattle-monitoring-system\":\n       waived = \"true\"\n    return { \n        \"waived\": waived,\n    }\n\n"
kind: ConfigMap
metadata:
    labels:
        app: pharos
    name: pharos-enrichers

