apiVersion: v1
data:
    enrichers.yaml: |
        order:
        {{- range .Values.enrichers.order | default list }}
          - {{ . }}
        {{- end }}
        sources:
          {{- range $key, $value := .Values.enrichers.definitions | default dict }}
          - name: {{ $key }}
            path: {{ $key }}-enricher.yaml
          {{- end }}

    {{- range $key, $value := .Values.enrichers.definitions | default dict }}
    {{ $key }}-enricher.yaml: |
      enricher:
        {{- range . }}
        - name: {{ .type }}
          config: {{ .name }}
          ref: {{ .ref | default "" }}
        {{- end }}
    {{- range $value }}
    {{ .name }}: |
    {{- if .content }}
    {{- .content | default "" | nindent 6 }}
    {{- else }}
    {{- if .file }}
    {{- .file | $.Files.Get | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
            
kind: ConfigMap
metadata:
    labels:
        app: pharos
    name: pharos-enrichers

