apiVersion: v1
kind: ConfigMap
metadata:
  name: pharos-config
  labels:
    app: pharos
data:
  .pharos.yaml: |
    {{- if .Values.redis.enabled }}
    redis: 
      dsn: pharos-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379
    {{- else }}
    redis: 
      dsn: {{ .Values.externalRedis.host | default "localhost" }}:{{ .Values.externalRedis.port | default 6379 }}
    {{- end }}
    {{- if .Values.postgres.enabled }}
    scanner:
      cacheEndpoint: redis://pharos-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379