apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pharos-controller
  name: pharos-controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: pharos-controller
  strategy: {}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: pharos-controller
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: pharos-controller
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args: ["http", "--config", "/config/.pharos.yaml"]
        ports:
          - containerPort: 8080
        env:
          - name: PHAROS_DATABASE_DSN
            valueFrom:
              secretKeyRef:
                name: postgres-connection
                key: dsn
          - name: APP_DATA_PATH
            value: "/pharos"
          - name: PHAROS_MAPPER_BASEPATH
            value: "/pharos/mappers"
        volumeMounts:
          - name: config-volume
            mountPath: /config/.pharos.yaml
            subPath: .pharos.yaml
          - name: mappers-volume
            mountPath: /pharos/mappers
          - name: enrichers-volume
            mountPath: /pharos/enrichers
      volumes:
        - name: config-volume
          configMap:
            name: pharos-config
        - name: enrichers-volume
          configMap:
            name: pharos-enrichers
        - name: mappers-volume
          configMap:
            name: pharos-mappers

