apiVersion: v1
kind: Service
metadata:
  name: {{ include "pharos.postgres.fullname" . }}
  labels:
    {{- include "pharos.postgres.labels" . | nindent 4 }}
    {{- with .Values.postgres.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.postgres.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
      {{- if and ( or (eq .Values.postgres.service.type "LoadBalancer") (eq .Values.postgres.service.type "NodePort") ) (.Values.postgres.service.nodePort) }}
      nodePort: {{ .Values.postgres.service.nodePort }}
      {{- end }}
  {{- if and (eq .Values.postgres.service.type "LoadBalancer") (.Values.postgres.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.postgres.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.postgres.service.type "LoadBalancer") (.Values.postgres.service.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml .Values.postgres.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.service.clusterIP }}
  clusterIP: {{ .Values.postgres.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "pharos.postgres.selectorLabels" . | nindent 4 }}
