
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pharos.fullname" . }}
spec:
  endpoints:
    - path: /api/metrics
      targetPort: 8080
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
        app: pharos-controller