apiVersion: v1
kind: Service
metadata:
  name: {{ include "pharos.fullname" . }}
  labels:
    {{- include "pharos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pharos-controller