

services:

  # see Taskfile.yaml for initialization of htpasswd and certificat for registry
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key

    volumes:
      - ./_runtest/certs:/certs
      - ./_runtest/htpasswd:/auth/htpasswd:ro
      - ./_registry:/var/lib/registry

  redis:
    image: redis:8.0.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel notice --requirepass $REDIS_PASSWORD
    volumes:
      - redisdb:/data

volumes:
  redisdb:
    driver: local
