

services:
  cache:
    image: redis:8.0.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel notice --requirepass $REDIS_PASSWORD
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
