# https://taskfile.dev

version: '3'

vars:
  REGISTRY_USER: pharos
  REGISTRY_PASSWORD: reg707
  PODEXE:
    sh: |
      if command -v docker >/dev/null 2>&1; then
        echo docker
      else
        echo podman
      fi

dotenv:
  - .env

silent: true

tasks:

  pod-up:
    desc: App start (compose)
    cmds:
      - echo "App up"
      - podman-compose -f docker-compose.yaml up

  pod-down:
    desc: App stop (compose)
    cmds:
      - echo "App down"
      - podman-compose -f docker-compose.yaml down

  grype-db:
    desc: Show Grype db
    cmds:
      - grype db list


  registry-init:
    desc: Populate local registry with images
    preconditions:
      - sh: command -v podman
        msg: "Podman is not installed or not in your PATH."
      - export PODEXE=runner
    vars:
      devdir: _runtest
    cmds:
      - echo "-----< Initialize local test deployment >-----"
      - 'echo "- devdir:  {{.devdir}}"'
      - 'echo "- podexe:  {{.PODEXE}}"'
      - mkdir -p {{.devdir}}
      - mkdir -p {{.devdir}}/certs
      - mkdir -p _registry

      # create registry htpasswd
      - echo "Generate registry htpasswd registry .."
      - '{{.PODEXE}} run --rm --entrypoint htpasswd httpd:2 -Bbn {{.REGISTRY_USER}} {{.REGISTRY_PASSWORD}} > {{.devdir}}/htpasswd'
      
      # create registry certificates
      - echo "Generate registry certificats .."
      - openssl req -newkey rsa:4096 -nodes -sha256 -addext "subjectAltName=DNS:localhost" -keyout {{.devdir}}/certs/domain.key -x509 -days 365 -out {{.devdir}}/certs/domain.crt -subj "/CN=localhost" 2>/dev/null

      # create registry certificates
      - echo "**** copy domain.crt to {{.PODEXE}} certificate to the client trust it ****"
      - echo "podman             cp {{.devdir}}/certs/domain.crt /etc/containers/certs.d/localhost:5000/ca.crt"
      - echo "podman (rootless)  cp {{.devdir}}/certs/domain.crt ~/.config/containers/certs.d/localhost:5000/ca.crt"

  registry-seed:
    desc: Seed local registry with images
    vars:
      images:
        # ghcr.io/digininja/dvwa:461b83a
        - dvwa:461b83a
        # docker.io/library/redis:8.0.2-alpine
        - redis:8.0.2-alpine
        # docker.io/library/busybox:1.35
        - busybox:1.35
        - busybox:1.37

    cmds:
      - podman login localhost:5000 -u {{.REGISTRY_USER}} -p {{.REGISTRY_PASSWORD}}
      - echo "load.."
      - for:
          var: images
        cmd: |
          {{.PODEXE}} tag {{.ITEM}} localhost:5000/{{.ITEM}}
          {{.PODEXE}} push --tls-verify=false localhost:5000/{{.ITEM}}


  scan:
    desc: Scan image [name], [tag] with grype, trivy, cdxgen
    requires:
      vars: [name,tag]
    vars:
      image:   docker.io/{{.name}}:{{.tag}}
      scanfile: _scans/{{.name}}/{{.name}}-{{.tag}}.scan
      sbomfile: _scans/{{.name}}/{{.name}}-{{.tag}}.sbom
    cmds:
      - 'echo "image:  {{.image}}"'
      - 'echo "outdir: {{.outdir}}"'
      - mkdir -p _scans
      - mkdir -p _scans/{{.name}}

      # Create cyclonedx SBOM with grype, trivy, cdxgetn
      - cdxgen --type docker {{.image}}                         -o {{.sbomfile}}.cdxgetn.sbom-cyclonedx.json
      - trivy image {{.image}}                 -f cyclonedx     -o {{.sbomfile}}.trivy.sbom-cyclonedx.json
      - syft {{.image}}                        -o cyclonedx-json > {{.sbomfile}}.syft.sbom-cyclonedx.json
      - syft {{.image}}                        -o syft-json      > {{.sbomfile}}.syft.sbom-syft.json

      # Scan sbom with Trivy
      - trivy sbom {{.sbomfile}}.trivy.sbom-cyclonedx.json --scanners vuln -f json -o {{.scanfile}}.trivy.scan-cyclonedx.json
      - trivy image {{.image}}                             --scanners vuln -f json -o {{.scanfile}}.trivy.scan-image.json

      # Scan sbom with grype
      - grype sbom:{{.sbomfile}}.syft.sbom-cyclonedx.json   -o json    > {{.scanfile}}.grype.scan-cyclondex-0.json
      - grype sbom:{{.sbomfile}}.trivy.sbom-cyclonedx.json   -o json    > {{.scanfile}}.grype.scan-cyclondex-1.json
      - grype {{.image}}       -o json    > {{.scanfile}}.grype.scan-image.json

  trivy-db:
    desc: Show trivy db
    vars:
      path: ~/Library/Caches/trivy/db/
    cmds:
      - echo "dir {{.path}}"
      - ls ~/Library/Caches/trivy/db/
