name: Build
on:
  push:
    branches: 
    - main
    - PH-4/*
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  ko-build:
    uses: metraction/github-actions/.github/workflows/ko-build.yaml@main
    secrets: inherit
        