<<<<<<< HEAD
name: Build
=======
name: Build with ko

>>>>>>> c457fd0 (Subscriber implemented)
on:
  push:
    branches: 
    - main
    - PH-1/*
    tags:
    - 'v*'

<<<<<<< HEAD
=======
  pull_request:
    branches: [ main ]

>>>>>>> c457fd0 (Subscriber implemented)
permissions:
  contents: read
  packages: write

jobs:
  ko-build:
    uses: metraction/github-actions/.github/workflows/ko-build.yaml@main
    secrets: inherit
        