# on: 
#   push:
#     branches:
#       - main1

# permissions:
#   contents: write
#   pull-requests: read

# jobs:
#   release-on-push:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#           fetch-tags: true
#       - name: update
#         id: update
#         run: |
#           git tag -l
#           git config --global user.email "actions@metraction.org"
#           git config --global user.name "GitHub Actions"
#           echo "Bumping version: $1"
#           oldtag=$(git describe --tags --abbrev=0 | sed 's/^v//')
#           IFS=. read -r major minor patch <<EOF
#           $oldtag
#           EOF

#           echo "old: $oldtag"
#           tag="$major.$minor.$((patch + 1))"
#           echo "new: $tag"
#           git tag -a "v$tag" -m "v$tag"
#           git push origin "v$tag"
#           echo "version=v$tag" >> "$GITHUB_OUTPUT"
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: ${{ steps.update.outputs.version }}
#           release_name: ${{ steps.update.outputs.version }}
#           body: |
#             Changes in this Release
#             - First Change
#             - Second Change
#           draft: false
#           prerelease: false