on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug
        run: |
          oldtag=$(git tag -l | tail -n 1 | sed 's/^v//g')
          IFS=. read -r version minor patch <<EOF
          $oldtag
          EOF

          case "$1" in
          patch) tag="$version.$minor.$((patch+1))"; ;;
          major) tag="$((version+1)).0.0"; ;;
          *)     tag="$version.$((minor+1)).0"; ;;
          esac

          echo $tag
