on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug
        run: |
          echo "Bumping version: $1"
          oldtag=$(git tag -l | tail -n 1 | sed 's/^v//g')
          IFS=. read -r major minor patch <<EOF
          $oldtag
          EOF

          echo "old: $oldtag"
          tag="$major.$minor.$((patch + 1))"
          echo "new: $tag"
          git tag -a "v$tag" -m "v$tag"
          git push origin "v$tag"